#!/bin/sh

if [ "$2" = "--light-theme" ]; then

  theme_0='#ffffff'
  theme_1='#000000'
else

  theme_0='#000000'
  theme_1='#ffffff'
fi

case $1 in

  --all)

    app_list=$(cat "$HOME"/.local/share/applications/*.desktop |\
      grep '^Name=.*\|^Exec=.*' | grep -vw 'Qube Settings\|qubes-vm-settings')


    chosen=$(echo "$app_list" | grep '^Name=.*' | cut -c 6- |\
      dmenu -f -m 0 -nb $theme_0 -nf $theme_1 -sb $theme_1 -sf $theme_0)

    if [ -n "$chosen" ]; then

      if ! $(echo "$app_list" | grep -A1 "$chosen" |\
        grep '^Exec=.*' | cut -c 6-); then exit 2; fi

      exit 0
    fi

    exit 1;;


  --only)

    focused_window=$(xdotool getwindowfocus)

    qube=$(xprop -id "$focused_window" | grep -w "_QUBES_VMNAME(STRING)" |\
      cut -f2 -d\")

    if [ -n "$qube" ]; then

      qube_label=$(qvm-ls --raw-data "$qube" -O LABEL)

      # Change some to a more readable color if needed.
      if [ "$qube_label" = "black" ]; then

        qube_label='#373737'

      elif [ "$qube_label" = "orange" ]; then

        qube_label='#f57900'

      elif [ "$qube_label" = "yellow" ]; then

        qube_label='#edd400'

      elif [ "$qube_label" = "green" ]; then

        qube_label='#73d216'
      fi

      app_list=$(cat "$HOME"/.local/share/qubes-appmenus/"$qube"/apps/*.desktop |\
        grep '^Name=.*\|^Exec=.*' |\
        grep -vw 'Qube Settings\|qubes-vm-settings')

      chosen=$(echo "$app_list" | grep '^Name=.*' | cut -f2 -d: |\
        dmenu -p "$qube:" -f -m 0 -nb $theme_0 -nf $theme_1 -sb "$qube_label" -sf $theme_1)

      if [ -n "$chosen" ]; then

        if ! $(echo "$app_list" | grep -A1 "$chosen" |\
          grep '^Exec=.*' | cut -c 6-); then exit 2; fi

        exit 0
      fi

      exit 1
    fi

    exit 2;;


  *)

    printf "qmenu-al [OPTION] (--light-theme)\n\n --all\n --only\n\n\nqmenu v1.2\n<https://github.com/sine3o14nnae/qmenu/>\n<https://gitlab.com/sine3o14nnae/qmenu/>\n\n"

    if [ "$1" = "--help" ]; then exit 0; else exit 2; fi
esac


# Note that the '-m 0' option in 'dmenu' is important
# for security, as it restricts it to monitor 0.
